app/src/components/discord-button.tsx
app/src/components/emotions.tsx
app/src/components/pokemon-thumbnail.tsx

A discussed in Discord
I simply sorted the portraits by name too. Better sorting should be possible.

Four minor tweak

---

app/graphql.schema.json
app/src/components/pokemon-thumbnail.tsx
app/src/generated/graphql.tsx
app/src/graphql/Carrousel.graphql
app/src/graphql/schema.graphqls

@keldaan-ag (assuming it is you that host sprites.pmdcollab.org), you will need to make sure that you update the server to include  [817d811b4e20e6217d4f256b18c34c83d902281d](https://github.com/PMDCollab/spritecollab-srv/commit/817d811b4e20e6217d4f256b18c34c83d902281d)

use previewEmotion instead of the Normal portrati

---

app/src/About.tsx
app/src/Home.tsx
app/src/style/app.css

- About page rewritten for accuracy and grammar (particularly to more accurately portray the distinction between PMDCollab and SpriteCollab)
- Title added to home page, along with a brief note on usage.

Update about page, home page banner

---

src/About.tsx

better about section

---

src/Home.tsx
src/components/bounty.tsx
src/components/credits.tsx
src/components/display-parameters.tsx
src/components/emotions.tsx
src/components/footer.tsx
src/components/lock.tsx
src/components/phaser/game-scene.ts
src/components/pokemon-carousel.tsx
src/components/pokemon-informations.tsx
src/components/pokemon-page.tsx
src/components/pokemon-ranking.tsx
src/components/pokemon-thumbnail.tsx
src/components/search.tsx
src/components/sprite-preview.tsx
src/generated/graphql.tsx
src/graphql/Carrousel.graphql

Reorganized some of the components with object destructuring and grouped the states in the home menu into a map
-also fixed portrait/sprite authors not showing because it wasn't in the graphql request for some reason

object destructure abuse + mapping states to object instead of passing by parameters individually

---

src/Home.tsx
src/components/pokemon-carousel.tsx
src/components/sprite-preview.tsx

fixing fully-featured sprite and portrait checkboxes

---

package-lock.json
src/Home.tsx
src/components/bounty.tsx
src/components/credits.tsx
src/components/display-parameters.tsx
src/components/pokemon-carousel.tsx
src/components/pokemon-ranking.tsx
src/components/pokemon-thumbnail.tsx
src/components/sprite-preview.tsx
src/generated/graphql.tsx
src/graphql/Carrousel.graphql
src/graphql/Keys.graphql
src/util.tsx

i forgot who asked for this but new checkboxes have been added to the main website (and show params/filter params have been grouped individually to prevent confusion) as well as the split form option to display all available forms with individual display information
and also forgot to convert conditional numbers to booleans so sometimes there's just a floating 0

completion filter checkboxes and visible sprite forms

---

src/components/pokemon-carousel.tsx
src/generated/graphql.tsx

we should probably find a fix for this but at least I remembered this time

fixing graphql any types

---

src/Home.tsx
src/components/display-parameters.tsx
src/components/pokemon-carousel.tsx
src/generated/graphql.tsx
src/graphql/Carrousel.graphql

added labels for parameters and fixed obsolete sprites being rendered anyways

ok this is the last pull request i need to make

---

src/components/pokemon-carousel.tsx
src/components/pokemon-thumbnail.tsx

it did a thing and it died so now it doesn't do that

fixed portrait/sprite bounty not fetching form information

---

src/components/credits.tsx
src/components/phaser/game-scene.ts
src/components/pokemon-informations.tsx
src/components/pokemon-page.tsx
src/components/sprite-preview.tsx

ignore quickstrike for sprite size
inline credits with download

selector for forms

---

src/components/pokemon-thumbnail.tsx
src/util.tsx

silly bug i totally forgot about

fixed text scaling from the initial name to individual names

---

index.html
src/Home.tsx
src/components/footer.tsx
src/components/pokemon-carousel.tsx
src/components/pokemon-informations.tsx
src/components/sprite-preview.tsx
src/generated/graphql.tsx
src/index.tsx
src/util.tsx

- XML loading used to happen once per game instance, now the XML loads once per pokemon page
- Error screen shows when the page is unable to fetch from spriteserver.pmdcollab.org
- Changed DateTimeUtc type to string manually

Error screen and XML loading

---

src/About.tsx

About fix with license

---

src/components/pokemon-thumbnail.tsx

quick hotfix #2 because i did a dumb dumb fumble

---

src/About.tsx
src/Home.tsx
src/components/pokemon-thumbnail.tsx
src/components/search.tsx
src/components/sprite-preview.tsx

- mobile view is shrunken down to fit up to 5 portraits and the bar has been added back
- grid in the about section no longer overlaps with the text

better mobile view

---

src/About.tsx
src/Home.tsx
src/components/pokemon-carousel.tsx
src/components/pokemon-page.tsx
src/components/pokemon-thumbnail.tsx
src/index.css

https://discord.com/channels/710190644152369162/787524304932831252/1212282850582331413

hyperlinked with credit

---

graphql.schema.json
src/components/pokemon-carousel.tsx
src/components/pokemon-thumbnail.tsx
src/generated/graphql.tsx
src/graphql/Carrousel.graphql
src/util.tsx

- manual query only shows up when forms are not split
- gp bounties now show properly when forms are not split

fixed manual query

---

graphql.schema.json
src/Contributors.tsx
src/Home.tsx
src/components/display-parameters.tsx
src/components/generate-credits.ts
src/components/pokemon-carousel.tsx
src/components/pokemon-ranking.tsx
src/components/pokemon-thumbnail.tsx
src/generated/graphql.tsx
src/graphql/Carrousel.graphql
src/types/enum.ts
src/util.tsx

FINALLY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
I sort of rushed the shopping cart feature so that it could just get done, so performance will probably be awful for people that are crediting. I will be looking for feedback so I can push a few more updates while this one is out, hopefully!
To open shopping cart, you need to add a search parameter to the website so that it directs to https://sprites.pmdcollab.org/#/?beta=true instead. This version of the site adds a checkbox that enters you into credits mode, allowing you to then select the monsters included in your ROM hack for crediting.
It is HEAVILY recommended to check "Split Forms" to ensure that all forms you use …

Shopping Cart

---

src/components/generate-credits.ts

https://discord.com/channels/710190644152369162/927492498295762954/1245044992964169810

fixed merging credits

---

src/Home.tsx
src/types/params.ts

the last pull request didn't deploy oops! tested locally with build this time and it should be ok

removed const type casting since it doesn't merge with a type array

---

src/ErrorPage.tsx
src/Home.tsx
src/components/generate-credits.ts
src/components/pokemon-carousel.tsx
src/components/pokemon-page.tsx
src/components/pokemon-thumbnail.tsx
src/index.css
src/index.tsx
src/util.tsx

as someone who had no idea i could just put all my refs into one big state so it wouldn't updated every click (or at least i think) i think this update was very warranted. if this works better than last time, I'll consider moving this to the main site

making credits run decently

---

src/components/pokemon-informations.tsx
src/components/pokemon-page.tsx
src/components/sprite-preview.tsx

https://discord.com/channels/710190644152369162/927492498295762954/1268702483262476402

displaying CopyOf animations on pokemon pages

---

src/components/display-parameters.tsx
src/components/pokemon-carousel.tsx
src/components/pokemon-informations.tsx
src/types/params.ts

missing portrait filter

---

graphql.schema.json
src/components/pokemon-carousel.tsx
src/generated/graphql.tsx
src/graphql/Carrousel.graphql
src/types/params.ts

missing sprite filter joins missing portrait filter into the battle as an echo fighter

missing sprite filter

---

src/components/sprite-preview.tsx

chainable copyof

---

src/About.tsx
src/Contributors.tsx
src/components/pokemon-carousel.tsx
src/components/sprite-preview.tsx
src/types/params.ts

added credits mode reference to about

---

src/Home.tsx

changed credit request
